version: "3.9"
services:
  php-env:
    build: .
    volumes:
    - ./src:/var/www/html
    ports:
      - 4000:80
  mysql_db:
    image: mysql:latest
    container_name: mysql_php
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: electric
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  mysql: